---
name: WebService-Validator-HTML-W3C
version: 0.18
author:
  - 'Struan Donald E<lt>struan@cpan.orgE<gt>'
  - 'L<http://www.exo.org.uk/code/>'
abstract: Access the W3Cs online HTML validator
license: perl
requires:
  Class::Accessor: 0
  LWP: 0
build_requires:
  Test::More: 0
provides:
  WebService::Validator::HTML::W3C:
    file: lib/WebService/Validator/HTML/W3C.pm
    version: 0.18
  WebService::Validator::HTML::W3C::Error:
    file: lib/WebService/Validator/HTML/W3C/Error.pm
  WebService::Validator::HTML::W3C::Warning:
    file: lib/WebService/Validator/HTML/W3C/Warning.pm
generated_by: Module::Build version 0.25
