--- #YAML:1.0
name: WebService-Validator-HTML-W3C
version: 0.03
license: perl
distribution_type: module
requires:
  Class::Accessor: 0
  LWP: 0
recommends: {}
build_requires:
  Test::More: 0
conflicts: {}
provides:
  WebService::Validator::HTML::W3C:
    file: lib/WebService/Validator/HTML/W3C.pm
    version: 0.03
  WebService::Validator::HTML::W3C::Error:
    file: lib/WebService/Validator/HTML/W3C/Error.pm
generated_by: Module::Build version 0.21
